parameters:
- name: buildConfigurations
  type: object
  default:
  - platform: win32
    configuration: Debug
    
jobs:
- job: Initialization
  steps:
  - script: echo 'init'
- job: Buildwin32_Debug
  steps:
  - script: echo 'build'
- job: x
  dependsOn:
  - Initialization
  - ${{ each buildConfiguration in parameters.buildConfigurations }}:
    - Build${{ buildConfiguration.platform }}_${{ buildConfiguration.configuration }}
  steps:
  - script: echo 'help'
